### ISSUE TITLE
whats the difference between this and this https://international.download.nvidia.com/Windows/broadcast/sdk/VFX/nvidia_video_effects_sdk_installer_v0.7.2_ampere.exe

### ISSUE THREAD

**Issue by Pickymarker** [TheJollyBeardo/OBS-RTX-SuperResolution#1]
whats the difference between this and this https://international.download.nvidia.com/Windows/broadcast/sdk/VFX/nvidia_video_effects_sdk_installer_v0.7.2_ampere.exe

**Comment by TheJollyBeardo** [comment]
> whats the difference between this and this https://international.download.nvidia.com/Windows/broadcast/sdk/VFX/nvidia_video_effects_sdk_installer_v0.7.2_ampere.exe

The link you've posted is the SDK itself for the 3000 RTX series, it's a requirement to have that installed for this plugin to even work. I have a link to this in the prerequisites.

That SDK by itself does nothing but provide the libraries and models that this plugin utilizes in the first place. OBS requires this same SDK for it's builtin greenscreen functionality, which this plugin is based on, just using different APIs in the SDK.

So, the difference really is one is an SDK that does nothing, one is an OBS plugin that is built on-top of that SDK to provide a filter utilizing the AI super resolution, regular upscaling, and artifact reduction features exposed by the SDK.

See these for more details as to what this plugin provides:
https://docs.nvidia.com/deeplearning/maxine/vfx-sdk-programming-guide/index.html#artifact-red-filter
https://docs.nvidia.com/deeplearning/maxine/vfx-sdk-programming-guide/index.html#super-res-filter
https://docs.nvidia.com/deeplearning/maxine/vfx-sdk-programming-guide/index.html#upscale-filter
